if (!window.html5ks) window.html5ks = {};
html5ks.characters = {
  name_only: {name: null, kind: adv},
  
  hi: {name: "Hisao", color: "#629276"},
  
  ha: {name: "Hanako", color: "#897CBF"},
  emi: {name: "Emi", color: "#FF8D7C"},
  rin: {name: "Rin", color: "#b14343"},
  li: {name: "Lilly", color: "#F9EAA0"},
  shi: {name: "Shizune", color: "#72ADEE"},
  mi: {name: "Misha", color: "#FF809F"},
  
  mi_shi: {name: "Shizune", color: "#FF809F"},
  mi_not_shi: {name: "{s}Shizune{/s} Misha", color: "#FF809F"},
  
  ke: {name: "Kenji", color: "#CC7C2A"},
  mu: {name: "Muto", color: "#FFFFFF"},
  nk: {name: "Nurse", color: "#FFFFFF"},
  no: {name: "Nomiya", color: "#E0E0E0"},
  yu: {name: "Yuuko", color: "#2c9e31"},
  sa: {name: "Sae", color: "#D4D4FF"},
  aki: {name: "Akira", color: "#eb243b"},
  hh: {name: "Hideaki", color: "#6299FF"},
  hx: {name: "Jigoro", color: "#99AACC"},
  emm: {name: "Meiko", color: "#995050"},
  sk: {name: "Shopkeep", color: "#7187A8"},
  mk: {name: "Miki", color: "#AD735E"},
  
  mystery: {name: "???"},
  
  ssh: {name: "Shizune", kind: shi, what_prefix: "[ ", what_suffix: " ]"},
  his: {name: "Hisao", kind: hi, what_prefix: "[ ", what_suffix: " ]"},
  
  ha_: {name: "Purple-haired girl", kind: ha},
  emi_: {name: "Twintails girl", kind: emi},
  rin_: {name: "Strange girl", kind: rin},
  li_: {name: "Wavy-haired girl", kind: li},
  mi_: {name: "Laughing girl", kind: mi},
  ke_: {name: "Bespectacled hallmate", kind: ke},
  mu_: {name: "Tall man", kind: mu},
  yu_: {name: "Librarian", kind: yu},
  no_: {name: "Silver-haired man", kind: no},
  sa_: {name: "Gallery owner", kind: sa},
  aki_: {name: "Well-dressed person", kind: aki},
  nk_: {name: "Smiling man", kind: nk},
  hx_: {name: "Huge man", kind: hx},
  hh_: {name: "Slim girl", kind: hh},
  emm_: {name: "Woman with braid", kind: emm},
  
  n: ReadbackNVL({name: null, 
       kind: "nvl",
       ctc: animBlink(im.Rotozoom("ui/ctc.png", 270, 1.0), {offset: 10, ypos: 560, xpos: 772}),
       ctc_position: "fixed"}),
  
  nb: {name: null, 
     kind: adv,
     ctc: null,
     what_color: "#666666",
     what_line_spacing: 8,
     what_prefix: "",
     what_suffix: "",
     show_function: say_wrapper,
     window_style: "b_nvl_window"},
  
  rinbabble: {name: null,
    kind: n,
    what_prefix: "{color: #FF8D7C}{b}Rin{/b}{/color}\n" + displayStrings.quote_outer_open,
    what_suffix: displayStringsquote_outer_close},
};
