language: c
python: "3.3"
node_js: "0.11"
env: MINIMAL=1 CFLAGS="-O2 -march=native -pipe" CXXFLAGS="-O2 -march=native -pipe" MAKEOPTS="-s" V=
before_install: ./.travis.sh before_install
install: ./.travis.sh install
script: make
notifications:
  email:
#    - alex_y_xu@yahoo.ca
  irc:
#    channels:
#      - "chat.freenode.net#html5ks"
#    on_success: change
#    on_failure: always
