language: c
python: '3.3'
node_js: '0.11'
env: MINIMAL=1 CFLAGS="-O2 -march=native -pipe" CXXFLAGS="-O2 -march=native -pipe"
  MAKEOPTS="-j8" FFMPEG="ffmpeg -t 00:00:05"
before_install: ./.travis.sh before_install
install: ./.travis.sh install
script: ./.travis.sh script
notifications:
  email:
    - alex_y_xu@yahoo.ca
  irc:
    "chat.freenode.net#html5ks"
    template:
      - "%{repository_name}#%{build_number} of %{commit} on %{branch} by %{author} took %{duration} and ended: %{message}"
      - "Compare: %{compare_url}"
      - "Build details: %{build_url}"
